const dataUrl = "data/processed/stock_sense_data.csv";
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const colors = ["#5e9b83", "#d66e59", "#719ea0"];
let rows = [], companies = [], selectedSymbol = "AAPL", selectedRange = "1y", visiblePriceData = [];

function parseCsv(text) { const out = [], row = []; let current = [], cell = "", quote = false; for (let i = 0; i < text.length; i += 1) { const c = text[i], n = text[i + 1]; if (c === '"' && quote && n === '"') { cell += c; i += 1; } else if (c === '"') quote = !quote; else if (c === "," && !quote) { current.push(cell); cell = ""; } else if ((c === "\n" || c === "\r") && !quote) { if (c === "\r" && n === "\n") i += 1; current.push(cell); if (current.length > 1) out.push(current); current = []; cell = ""; } else cell += c; } if (cell || current.length) { current.push(cell); out.push(current); } const [headers, ...records] = out; return records.map((r) => Object.fromEntries(headers.map((h, i) => [h, r[i] ?? ""]))); }
const money = (v) => `$${Number(v).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const pct = (v) => `${Number(v) > 0 ? "+" : ""}${Number(v).toFixed(1)}%`;
const status = (v) => Number(v) > 0 ? "positive" : Number(v) < 0 ? "negative" : "neutral";
const dataFor = (symbol) => rows.filter((r) => r.symbol === symbol);
const subset = (data, period) => data.slice(-({ "1m": 22, "6m": 126, "1y": 252, "3y": 756, all: data.length }[period]));

function fillSelect(select, selected) { select.innerHTML = companies.map((c) => `<option value="${c.symbol}" ${c.symbol === selected ? "selected" : ""}>${c.symbol} · ${c.company}</option>`).join(""); }
function chartGeometry(svg, series, key) { const width = Math.max(svg.clientWidth || 760, 320), height = svg.clientHeight || 300, m = { top: 20, right: 14, bottom: 48, left: 60 }, values = series.flatMap((s) => s.data.map((p) => Number(p[key]))).filter(Number.isFinite), min = Math.min(...values), max = Math.max(...values), pad = Math.max((max - min) * .12, 1), low = min - pad, high = max + pad, x = (i, l) => m.left + i / Math.max(l - 1, 1) * (width - m.left - m.right), y = (v) => m.top + (high - v) / (high - low) * (height - m.top - m.bottom); return { width, height, m, low, high, x, y }; }
function drawLines(svg, mainData, key, series, { dipMarkers = false, onHover, xTitle = "Date", yTitle = "Value" } = {}) {
  const g = chartGeometry(svg, series, key), { width, height, m, low, high, x, y } = g;
  const grids = [0, .5, 1].map((f) => { const v = low + (high - low) * f, yy = y(v), label = key === "close" ? money(v) : v.toFixed(0); return `<line class="chart-grid" x1="${m.left}" x2="${width - m.right}" y1="${yy}" y2="${yy}"/><text class="chart-axis" x="${m.left - 8}" y="${yy + 4}" text-anchor="end">${label}</text>`; }).join("");
  const dates = [0, .5, 1].map((f) => { const i = Math.round((mainData.length - 1) * f); return `<text class="chart-axis" x="${x(i, mainData.length)}" y="${height - 21}" text-anchor="middle">${mainData[i]?.date.slice(0, 7) || ""}</text>`; }).join("");
  const paths = series.map((s, n) => { const path = s.data.map((p, i) => `${i ? "L" : "M"}${x(i, s.data.length)},${y(Number(p[key]))}`).join(" "), last = s.data.at(-1); return `<path class="comparison-line" d="${path}" stroke="${s.color}"/><circle cx="${x(s.data.length - 1, s.data.length)}" cy="${y(Number(last[key]))}" r="4" fill="${s.color}"/><text class="chart-axis" x="${width - m.right}" y="${y(Number(last[key])) - 8 - n * 13}" text-anchor="end" fill="${s.color}">${s.name}</text>`; }).join("");
  const dips = dipMarkers ? mainData.filter((d) => d.dip_flag === "True").map((d) => { const i = mainData.indexOf(d); return `<circle class="dip-marker" cx="${x(i, mainData.length)}" cy="${y(Number(d[key]))}" r="4.2"/>`; }).join("") : "";
  const titles = `<text class="chart-axis chart-title" x="${width / 2}" y="${height - 3}" text-anchor="middle">${xTitle}</text><text class="chart-axis chart-title" transform="translate(13 ${height / 2}) rotate(-90)" text-anchor="middle">${yTitle}</text>`;
  svg.setAttribute("viewBox", `0 0 ${width} ${height}`); svg.innerHTML = `${grids}${dates}${paths}${dips}${titles}<line class="hover-guide" id="${svg.id}Guide" y1="${m.top}" y2="${height - m.bottom}" opacity="0"/><rect class="chart-hit" x="${m.left}" y="${m.top}" width="${width - m.left - m.right}" height="${height - m.top - m.bottom}"/>`;
  const hit = svg.querySelector(".chart-hit"), guide = svg.querySelector(".hover-guide");
  hit.addEventListener("pointermove", (event) => { const rect = svg.getBoundingClientRect(), px = (event.clientX - rect.left) / rect.width * width, idx = Math.max(0, Math.min(mainData.length - 1, Math.round((px - m.left) / (width - m.left - m.right) * (mainData.length - 1)))); guide.setAttribute("x1", x(idx, mainData.length)); guide.setAttribute("x2", x(idx, mainData.length)); guide.setAttribute("opacity", "1"); onHover?.(idx, event, g); });
  hit.addEventListener("pointerleave", () => { guide.setAttribute("opacity", "0"); });
  return g;
}
function moveTooltip(tooltip, event, wrap) { const box = wrap.getBoundingClientRect(); tooltip.style.left = `${Math.max(8, Math.min(event.clientX - box.left + 14, box.width - 215))}px`; tooltip.style.top = `${Math.max(20, event.clientY - box.top - 78)}px`; tooltip.hidden = false; }
function setFocus(index) { const d = visiblePriceData[index]; if (!d) return; const svg = $("#priceChart"), guide = $("#priceChartGuide"), width = Number(svg.getAttribute("viewBox").split(" ")[2]), margin = 60, x = margin + index / Math.max(visiblePriceData.length - 1, 1) * (width - margin - 14); guide.setAttribute("x1", x); guide.setAttribute("x2", x); guide.setAttribute("opacity", "1"); $("#timelineSlider").value = index; $("#timelineDate").textContent = d.date; $("#timelineDetail").innerHTML = `<b>${money(d.close)}</b> · ${pct(d.return_1d_pct)} in one day${d.dip_flag === "True" ? " · <span class=\"negative\">Dip Watch flagged</span>" : ""}`; }
function updateExplore() { const all = dataFor(selectedSymbol), last = all.at(-1); visiblePriceData = subset(all, selectedRange); $("#selectedSymbol").textContent = last.symbol; $("#selectedCompany").textContent = last.company; $("#selectedSector").textContent = last.sector; [["#latestClose", money(last.close), "neutral"], ["#return1d", pct(last.return_1d_pct), status(last.return_1d_pct)], ["#return1m", pct(last.return_1m_pct), status(last.return_1m_pct)], ["#return1y", pct(last.return_1y_pct), status(last.return_1y_pct)], ["#drawdown", pct(last.drawdown_from_52w_high_pct), status(last.drawdown_from_52w_high_pct)]].forEach(([id, text, className]) => { const el = $(id); el.textContent = text; el.className = className; }); $("#chartLabel").textContent = `${visiblePriceData[0].date} — ${last.date}`; drawLines($("#priceChart"), visiblePriceData, "close", [{ data: visiblePriceData, color: "#b7d7c8", name: "" }], { dipMarkers: true, xTitle: "Date", yTitle: "Closing price (USD)", onHover: (i, event) => { const d = visiblePriceData[i], tip = $("#priceTooltip"); tip.innerHTML = `<b>${d.date}</b><br>${money(d.close)} · ${pct(d.return_1d_pct)} today${d.dip_flag === "True" ? "<br><span class=\"negative\">● Dip Watch signal</span>" : ""}`; moveTooltip(tip, event, $("#priceChart").parentElement); setFocus(i); } }); const slider = $("#timelineSlider"); slider.max = visiblePriceData.length - 1; setFocus(visiblePriceData.length - 1); }
function updateCompare() { const symbols = [$("#compareA").value, $("#compareB").value, $("#compareC").value], series = symbols.map((symbol, i) => { const data = dataFor(symbol).slice(-252), first = Number(data[0].close); return { symbol, color: colors[i], name: symbol, data: data.map((d) => ({ ...d, indexed: Number(d.close) / first * 100 })) }; }); drawLines($("#compareChart"), series[0].data, "indexed", series, { xTitle: "Date", yTitle: "Indexed return (100 = start, 110 = +10%)", onHover: (i, event) => { const tip = $("#compareTooltip"), date = series[0].data[i].date; tip.innerHTML = `<b>${date}</b><br>${series.map((s) => `<span style=\"color:${s.color}\">●</span> ${s.symbol}: ${s.data[i].indexed.toFixed(1)}`).join("<br>")}`; moveTooltip(tip, event, $("#compareChart").parentElement); } }); $("#compareSummary").innerHTML = series.map((s) => { const last = s.data.at(-1), change = last.indexed - 100; return `<article><span style="color:${s.color}">● ${s.symbol}</span><strong class="${status(change)}">${pct(change)}</strong><small>${last.company} · ${last.sector}</small></article>`; }).join(""); }
function renderSectorInsight(sector) { const latest = rows.filter((r) => r.date === rows.at(-1).date && r.sector === sector); $("#sectorInsight").innerHTML = `<strong>${sector}</strong>${latest.map((r) => `<span>${r.symbol} <b class="${status(r.return_1y_pct)}">${pct(r.return_1y_pct)}</b></span>`).join("")}`; $$(".sector-item").forEach((b) => b.classList.toggle("active", b.dataset.sector === sector)); }
function renderSectors() { const date = rows.at(-1).date, latest = rows.filter((r) => r.date === date), items = [...new Set(latest.map((r) => r.sector))].map((sector) => { const vals = latest.filter((r) => r.sector === sector).map((r) => Number(r.return_1y_pct)); return { sector, value: vals.reduce((a, b) => a + b, 0) / vals.length }; }).sort((a, b) => b.value - a.value); $("#sectorList").innerHTML = items.map((i) => `<button class="sector-item" data-sector="${i.sector}"><span>${i.sector}</span><strong class="${status(i.value)}">${pct(i.value)}</strong></button>`).join(""); $$(".sector-item").forEach((b) => b.addEventListener("click", () => renderSectorInsight(b.dataset.sector))); renderSectorInsight(items[0].sector); }
function renderMap() { const data = rows.filter((r) => r.date === rows.at(-1).date), svg = $("#marketMap"), width = Math.max(svg.clientWidth || 800, 320), height = svg.clientHeight || 440, m = { top: 25, right: 20, bottom: 48, left: 52 }, xs = data.map((d) => Number(d.return_1y_pct)), ys = data.map((d) => Number(d.drawdown_from_52w_high_pct)), xMin = Math.min(-20, ...xs) - 5, xMax = Math.max(40, ...xs) + 5, yMin = Math.min(-45, ...ys) - 3, yMax = 2, x = (v) => m.left + (v - xMin) / (xMax - xMin) * (width - m.left - m.right), y = (v) => m.top + (yMax - v) / (yMax - yMin) * (height - m.top - m.bottom), radius = (v) => Math.max(5, Math.min(16, Math.log10(Number(v) + 1) - 3)); const ticks = [0, .5, 1].map((f) => { const xv = xMin + (xMax - xMin) * f, xx = x(xv); return `<line class="map-grid" x1="${xx}" x2="${xx}" y1="${m.top}" y2="${height - m.bottom}"/><text class="map-axis" x="${xx}" y="${height - 12}" text-anchor="middle">${xv.toFixed(0)}%</text>`; }).join(""); const zero = `<line class="map-zero" x1="${x(0)}" x2="${x(0)}" y1="${m.top}" y2="${height - m.bottom}"/><line class="map-zero" x1="${m.left}" x2="${width - m.right}" y1="${y(0)}" y2="${y(0)}"/>`; const bubbles = data.map((d) => `<circle class="map-bubble" data-symbol="${d.symbol}" cx="${x(Number(d.return_1y_pct))}" cy="${y(Number(d.drawdown_from_52w_high_pct))}" r="${radius(d.volume)}" tabindex="0" role="button" aria-label="${d.company}, ${pct(d.return_1y_pct)} one-year return"></circle>`).join(""); svg.setAttribute("viewBox", `0 0 ${width} ${height}`); svg.innerHTML = `${ticks}${zero}<text class="map-axis" x="${width / 2}" y="${height - 1}" text-anchor="middle">one-year return</text><text class="map-axis" x="${m.left}" y="12">closer to 52-week high ↑</text>${bubbles}`; $$(".map-bubble").forEach((b) => { const d = data.find((r) => r.symbol === b.dataset.symbol); const show = (event) => { const tip = $("#mapTooltip"); tip.innerHTML = `<b>${d.symbol} · ${d.company}</b><br>1-year return: ${pct(d.return_1y_pct)}<br>From 52-week high: ${pct(d.drawdown_from_52w_high_pct)}`; moveTooltip(tip, event, $("#marketMap").parentElement); }; b.addEventListener("pointermove", show); b.addEventListener("pointerleave", () => { $("#mapTooltip").hidden = true; }); b.addEventListener("click", () => { selectedSymbol = d.symbol; $("#companySelect").value = d.symbol; updateExplore(); $("#explore").scrollIntoView({ behavior: "smooth" }); }); }); }
function renderDips() { const list = rows.filter((r) => r.dip_flag === "True").sort((a, b) => b.date.localeCompare(a.date)).slice(0, 7); $("#dipTable").innerHTML = list.map((r) => `<tr><td>${r.date}</td><td><span class="dip-company">${r.symbol}</span> · ${r.company}</td><td class="negative">${pct(r.return_1d_pct)}</td><td>${Number(r.volume_vs_30d_avg).toFixed(1)}×</td></tr>`).join(""); }
function historicalDipOutcomes(sector = "all") { const selected = companies.filter((company) => sector === "all" || company.sector === sector); return selected.flatMap((company) => { const history = dataFor(company.symbol); return history.flatMap((row, index) => { const later = history[index + 21]; if (row.dip_flag !== "True" || !later) return []; return [{ ...row, outcome_21d_pct: (Number(later.close) / Number(row.close) - 1) * 100 }]; }); }); }
function renderOutcomes() { const sector = $("#outcomeSector").value, outcomes = historicalDipOutcomes(sector), positive = outcomes.filter((d) => d.outcome_21d_pct > 0), negative = outcomes.filter((d) => d.outcome_21d_pct < 0), flat = outcomes.filter((d) => d.outcome_21d_pct === 0), total = outcomes.length, share = (items) => total ? items.length / total * 100 : 0, median = [...outcomes].map((d) => d.outcome_21d_pct).sort((a, b) => a - b).at(Math.floor(total / 2)) || 0, sectorName = sector === "all" ? "all selected sectors" : sector; $("#outcomeBars").innerHTML = `<div class="outcome-bar-row"><div><span>Ended higher</span><strong class="positive">${positive.length} events · ${share(positive).toFixed(0)}%</strong></div><div class="outcome-track"><i class="outcome-fill positive-fill" style="width:${share(positive)}%"></i></div></div><div class="outcome-bar-row"><div><span>Ended lower</span><strong class="negative">${negative.length} events · ${share(negative).toFixed(0)}%</strong></div><div class="outcome-track"><i class="outcome-fill negative-fill" style="width:${share(negative)}%"></i></div></div>${flat.length ? `<p class="outcome-flat">${flat.length} event${flat.length === 1 ? "" : "s"} ended unchanged.</p>` : ""}<p class="outcome-unit">Bar length = share of usable historical Dip Watch events. Green/red shows the price direction 21 trading days after each flag.</p>`; $("#outcomeSummary").innerHTML = `Among <b>${total} usable historical Dip Watch events</b> in <b>${sectorName}</b>, ${positive.length} (${share(positive).toFixed(0)}%) were higher and ${negative.length} (${share(negative).toFixed(0)}%) were lower 21 trading days later. The median follow-up return was <b class="${status(median)}">${pct(median)}</b>. Use this result to ask better questions about a new drop; do not treat it as proof of a future outcome.`; }
function renderDecisionAction() { const cause = $("#dipCause").value, fundamentals = $("#dipFundamentals").value, concentration = $("#dipConcentration").value, output = $("#decisionOutput"); if (cause === "unknown") { output.innerHTML = "<b>Next step: learn what caused the drop.</b><p>Read the relevant earnings release or credible news coverage. Write down whether the move followed earnings, guidance, economic news, or a company-specific event before using the historical chart.</p>"; return; } if (fundamentals === "yes") { output.innerHTML = "<b>Next step: study how the business changed.</b><p>Make a short note on what changed in revenue, profit, guidance, debt, or competition. A historical rebound rate does not outweigh direct evidence that the business may have changed.</p>"; return; } if (concentration !== "no") { output.innerHTML = "<b>Next step: practice diversification.</b><p>Choose one company from a different sector and compare it first. This helps you learn whether the idea adds a new perspective instead of repeating the same sector exposure.</p>"; return; } output.innerHTML = "<b>Next step: practice a peer comparison.</b><p>Compare the company’s one-year return, distance from its 52-week high, and two peers. Record the cause of the dip and the sector result, then keep it as a learning case—not a buy/sell conclusion.</p>"; }
function renderCounts() { $("#companyCount").textContent = companies.length; $("#sectorCount").textContent = new Set(companies.map((c) => c.sector)).size; $("#dipCount").textContent = rows.filter((r) => r.dip_flag === "True").length.toLocaleString(); $("#yearCount").textContent = ((new Date(rows.at(-1).date) - new Date(rows[0].date)) / (365.25 * 86400000)).toFixed(1); }
async function init() { try { const response = await fetch(dataUrl); if (!response.ok) throw Error("Could not load data"); rows = parseCsv(await response.text()); companies = [...new Map(rows.map((r) => [r.symbol, { symbol: r.symbol, company: r.company, sector: r.sector }])).values()].sort((a, b) => a.company.localeCompare(b.company)); fillSelect($("#companySelect"), selectedSymbol); fillSelect($("#compareA"), "AAPL"); fillSelect($("#compareB"), "MSFT"); fillSelect($("#compareC"), "NVDA"); $("#outcomeSector").insertAdjacentHTML("beforeend", [...new Set(companies.map((company) => company.sector))].sort().map((sector) => `<option value="${sector}">${sector}</option>`).join("")); $("#companySelect").addEventListener("change", (e) => { selectedSymbol = e.target.value; updateExplore(); }); $$(".range-buttons button").forEach((b) => b.addEventListener("click", () => { $$(".range-buttons button").forEach((x) => x.classList.remove("active")); b.classList.add("active"); selectedRange = b.dataset.range; updateExplore(); })); $("#timelineSlider").addEventListener("input", (e) => setFocus(Number(e.target.value))); ["#compareA", "#compareB", "#compareC"].forEach((id) => $(id).addEventListener("change", updateCompare)); $("#outcomeSector").addEventListener("change", renderOutcomes); ["#dipCause", "#dipFundamentals", "#dipConcentration"].forEach((id) => $(id).addEventListener("change", renderDecisionAction)); window.addEventListener("resize", () => { updateExplore(); updateCompare(); renderMap(); }); updateExplore(); updateCompare(); renderSectors(); renderMap(); renderDips(); renderOutcomes(); renderDecisionAction(); renderCounts(); } catch (error) { $("#explore .explorer").innerHTML = "<p>We could not load the project dataset. Start the site through a local web server so the CSV can be read.</p>"; } }
init();
