const decisionBrief = document.createElement("section");
decisionBrief.className = "decision-brief shell";
decisionBrief.innerHTML = `<div class="decision-kicker"><span class="eyebrow">DECISION BRIEF</span><h2>A financial-literacy tool,<br /><em>not a stock-picking tool.</em></h2></div><div class="decision-copy"><div><span>Intended user</span><p>Student investment clubs, community financial-literacy groups, and workshop leaders supporting beginner investors.</p></div><div><span>Problem</span><p>Beginners can see a price change but may not know whether they should pause, learn what caused it, compare peers, or move on.</p></div><div><span>Learning decision supported</span><p><b>What is the most useful next thing to learn after a large price move?</b> The site helps a learner choose a next learning step—not decide whether to buy or sell.</p></div></div><div class="decision-path"><span>Use the site in this order</span><ol><li><b>Explore</b> the price move and volume.</li><li><b>Compare</b> the company with peers and its sector.</li><li><b>Check</b> the historical dip outcomes.</li><li><b>Choose</b> your next learning step in the guide below.</li></ol></div>`;
document.querySelector(".snapshot").before(decisionBrief);

const findings = document.createElement("section");
findings.className = "findings-section shell";
findings.innerHTML = `<div class="section-intro"><div><p class="eyebrow">DECISION FINDINGS</p><h2>What this sample<br /><em>makes visible.</em></h2></div><p>These are observations from 33 selected companies and are designed to guide learning and research—not to predict future market returns.</p></div><div class="finding-grid"><article><span>01 / Sector context matters</span><h3>Sector returns did not move together.</h3><p>The selected Energy companies had the strongest average one-year return in this sample, while Consumer Discretionary was weakest. This shows why a beginner should compare a stock with broader sector context instead of looking at one ticker alone.</p></article><article><span>02 / A “dip” is not one thing</span><h3>Large down days need a reason.</h3><p>The dataset contains 348 historical Dip Watch observations. A large decline with above-average volume can be a useful moment to study earnings, news, and business conditions—but it does not prove a stock is a bargain.</p></article><article><span>03 / Same sector, different result</span><h3>Peer companies can still diverge.</h3><p>The indexed comparison chart shows that companies with a similar industry label can have very different one-year paths. Company-specific information still matters.</p></article></div><div class="recommendation-bar"><div><p class="eyebrow">PRACTICAL RECOMMENDATIONS</p><h3>For a student investment club or financial-literacy workshop</h3></div><ol><li><b>Teach comparisons before picks.</b> Have learners compare at least two companies and a sector before focusing on one popular stock.</li><li><b>Use a Dip Watch research checklist.</b> Ask what changed, what news or earnings occurred, and whether the company still fits a diversified portfolio.</li><li><b>Teach return and drawdown together.</b> A stock can have a strong one-year return and still be below its recent high; both views help prevent overconfident conclusions.</li></ol></div>`;
document.querySelector(".compare").before(findings);
