const sourceNote = document.querySelector(".source-note");
sourceNote.textContent = "The project filtered the original dataset to 33 selected companies, limited it to January 2021 through September 2026, sorted records by company and date, and joined company-sector information by ticker symbol. It then calculated the return, volume, drawdown, and Dip Watch fields. The website reads this cleaned project dataset rather than querying Kaggle live; the submitted data includes the cleaned daily records and a separate company/sector lookup file.";

const comparisonSection = document.createElement("section");
comparisonSection.className = "note-section shell";
comparisonSection.innerHTML = `<div class="note-label"><span>03</span><p>COMPARISONS</p></div><div class="note-content"><h2>How to read the comparison charts</h2><p>The three-company comparison graph resets each selected company to 100 at the beginning of the one-year period. This is important because stock prices are very different. A $300 stock is not automatically doing better than a $30 stock. Starting all three at 100 shows their percentage movement on the same scale.</p><p>The one-year sector return list averages the three selected companies in each sector. It is not a complete measure of every company in that sector, but it is a useful starting point for looking at broader trends. For example, when AI investment and demand become a major story, technology-related companies may move together or react differently. When oil prices, supply disruptions, wars, or other energy news affect the world, energy companies may become especially interesting to compare. The goal is to see whether a move looks company-specific or part of a wider sector trend.</p><div class="comparison-callout"><span>Good questions to ask</span><p>Is this company moving differently from similar businesses? Did multiple sectors react? What news or business changes could explain the trend?</p></div></div>`;
const reflection = document.querySelector(".reflection");
reflection.before(comparisonSection);
document.querySelector(".reflection .eyebrow").textContent = "04 / REFLECTION";
document.querySelector(".limitations .note-label span").textContent = "05";
